include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/app.router.dart"
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    sort_pub_dependencies: false